# Generated by Django 4.0.4 on 2022-06-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='拠点')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='チャンネル')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.base', verbose_name='拠点')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部署')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.base', verbose_name='拠点')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_id', models.CharField(max_length=30, verbose_name='SlackID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.base', verbose_name='拠点')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.department', verbose_name='部署')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='投稿日時')),
                ('text', models.TextField(max_length=30, verbose_name='投稿')),
                ('score', models.DecimalField(decimal_places=16, max_digits=16, verbose_name='スコア')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.channel', verbose_name='チャンネル')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.employee', verbose_name='メンバー')),
            ],
        ),
    ]
