# Generated by Django 4.0.4 on 2022-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(default='', max_length=50, verbose_name='チャンネルID'),
        ),
    ]
