# Generated by Django 4.0.4 on 2022-07-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_post_score_remove_post_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('channel', 'created_at'), name='channel_date_unique'),
        ),
    ]
