# Generated by Django 4.1 on 2022-08-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_post_channel_date_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='analytics.department', verbose_name='部署'),
        ),
    ]
