# Generated by Django 4.1 on 2022-10-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.organization', verbose_name='団体'),
        ),
        migrations.AddField(
            model_name='channel',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.organization', verbose_name='団体'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.organization', verbose_name='団体'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.organization', verbose_name='団体'),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.organization', verbose_name='団体'),
        ),
    ]
